# Generated by Django 4.2.15 on 2024-08-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_copy_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
